[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "/"

[dev]
  command = "npm run dev"
  port = 5173  # Default Vite port
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
